### ISSUE TITLE
EOFError on colab

### ISSUE THREAD

**Issue by rbychn** [camenduru/wav2lip-colab#2]
`Using cuda for inference.
Reading video frames...
Number of frames available for inference: 520
/usr/local/lib/python3.8/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "/usr/local/lib/python3.8/dist-packages/soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.8/dist-packages/soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening '/content/audio.wav': Format not recognised.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 280, in <module>
    main()
  File "inference.py", line 224, in main
    wav = audio.load_wav(args.audio, 16000)
  File "/content/Wav2Lip/audio.py", line 10, in load_wav
    return librosa.core.load(path, sr=sr)[0]
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/usr/local/lib/python3.8/dist-packages/audioread/__init__.py", line 127, in audio_open
    return BackendClass(path)
  File "/usr/local/lib/python3.8/dist-packages/audioread/rawread.py", line 62, in __init__
    self._file = aifc.open(self._fh)
  File "/usr/lib/python3.8/aifc.py", line 917, in open
    return Aifc_read(f)
  File "/usr/lib/python3.8/aifc.py", line 358, in __init__
    self.initfp(f)
  File "/usr/lib/python3.8/aifc.py", line 314, in initfp
    chunk = Chunk(file)
  File "/usr/lib/python3.8/chunk.py", line 63, in __init__
    raise EOFError
EOFError
[18]
0s
`

**Comment by Kingcartoons** [comment]
You need to change the file name of the audio or the video
